Repository emilk/egui, pull requests merged in 2025-10, with the labels that each got.

#7573 Add `Ui::take_available_space()` helper function, which sets the Ui's minimum size to the available space
  crates/egui/src/containers/panel.rs
  crates/egui/src/ui.rs
Labels: docs and examples, egui, dev-experience

#7580 Update wgpu to 27.0.0
  Cargo.lock
  Cargo.toml
  crates/egui-wgpu/src/setup.rs
  crates/egui_kittest/src/texture_to_image.rs
  crates/egui_kittest/src/wgpu.rs
  deny.toml
Labels: egui-wgpu, dependencies

#7589 Fix stuck menu when submenu vanishes
  crates/egui/src/containers/menu.rs
  crates/egui/src/containers/popup.rs
  crates/egui_demo_lib/src/demo/popups.rs
  crates/egui_kittest/tests/regression_tests.rs
Labels: bug, egui

#7595 CI: use latest typos
  .github/workflows/spelling_and_links.yml
  crates/egui/src/viewport.rs
  crates/egui_extras/src/layout.rs
  crates/epaint/src/text/fonts.rs
Labels: CI, exclude from changelog

#7594 clean up the clippy.toml:s
  clippy.toml
  scripts/clippy_wasm/clippy.toml
Labels: exclude from changelog, dev-experience

#7600 Inline log format args
  crates/eframe/src/epi.rs
  crates/eframe/src/native/file_storage.rs
  crates/eframe/src/web/events.rs
  crates/egui-wgpu/src/capture.rs
  crates/egui-wgpu/src/renderer.rs
  crates/egui-wgpu/src/setup.rs
  crates/egui-winit/src/lib.rs
  crates/egui_demo_app/src/apps/custom3d_glow.rs
  crates/egui_glow/examples/pure_glow.rs
  crates/egui_glow/src/lib.rs
  crates/egui_glow/src/painter.rs
  crates/egui_glow/src/shader_version.rs
  crates/egui_glow/src/vao.rs
  crates/egui_glow/src/winit.rs
  crates/egui_kittest/src/snapshot.rs
Labels: refactor, exclude from changelog

#7597 Fix preview build on contributor PRs
  .github/workflows/preview_build.yml
  .github/workflows/preview_comment.yml
Labels: CI, exclude from changelog

#7602 Use software texture filtering in kittest
  crates/eframe/src/native/wgpu_integration.rs
  crates/egui-wgpu/src/egui.wgsl
  crates/egui-wgpu/src/renderer.rs
  crates/egui_demo_app/tests/snapshots/imageviewer.png
  crates/egui_demo_lib/tests/snapshots/demos/Clipboard Test.png
  crates/egui_demo_lib/tests/snapshots/demos/Scene.png
  crates/egui_demo_lib/tests/snapshots/image_blending/image_x1.png
  crates/egui_demo_lib/tests/snapshots/image_blending/image_x2.png
  crates/egui_demo_lib/tests/snapshots/rendering_test/dpi_1.00.png
  crates/egui_demo_lib/tests/snapshots/rendering_test/dpi_1.25.png
  crates/egui_demo_lib/tests/snapshots/rendering_test/dpi_1.50.png
  crates/egui_demo_lib/tests/snapshots/rendering_test/dpi_1.67.png
  crates/egui_demo_lib/tests/snapshots/rendering_test/dpi_1.75.png
  crates/egui_demo_lib/tests/snapshots/rendering_test/dpi_2.00.png
  crates/egui_demo_lib/tests/snapshots/tessellation_test/Additive rectangle.png
  crates/egui_demo_lib/tests/snapshots/tessellation_test/Blurred stroke.png
  crates/egui_demo_lib/tests/snapshots/tessellation_test/Blurred.png
  crates/egui_demo_lib/tests/snapshots/tessellation_test/Minimal rounding.png
  crates/egui_demo_lib/tests/snapshots/tessellation_test/Normal.png
  crates/egui_demo_lib/tests/snapshots/tessellation_test/Thick stroke, minimal rounding.png
  crates/egui_demo_lib/tests/snapshots/tessellation_test/Thin filled.png
  crates/egui_demo_lib/tests/snapshots/tessellation_test/Thin stroked.png
  crates/egui_demo_lib/tests/snapshots/widget_gallery_dark_x1.png
  crates/egui_demo_lib/tests/snapshots/widget_gallery_dark_x2.png
  crates/egui_demo_lib/tests/snapshots/widget_gallery_light_x1.png
  crates/egui_demo_lib/tests/snapshots/widget_gallery_light_x2.png
Labels: egui-wgpu, egui_kittest

#7611 Use custom github token for commiting snapshots
  .github/workflows/update_kittest_snapshots.yml
Labels: CI
